services:
  targets-stream:
    build: .
    image: spire-targets-stream:latest
    env_file: .env
    environment:
      TZ: Asia/Jakarta
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./state:/app/state
    restart: unless-stopped
